# Generated by Django 5.1.5 on 2025-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Цена за лист'),
        ),
    ]
